# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Marvel-API' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Marvel-API
  pod 'Alamofire', '~> 5.2'

  target 'Marvel-APITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
